name: CI Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_S3_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_S3_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_S3_REGION: ${{ vars.AWS_REGION }}
  AWS_S3_BUCKET: ${{ vars.AWS_BUCKET }}
  AWS_S3_PRESIGNED_URL_EXPIRATION: ${{ vars.AWS_EXPIRATION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests and generate coverage
        run: ./gradlew test
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}